### ISSUE TITLE
will we have a q&a tool?

### ISSUE THREAD

**Issue by ltalirz** [crazy4pi314/scipy-vscode-tutorial#12]
For tutorials, I've found that having a built-in Q&A tool (e.g. like [the one in zoom](https://support.zoom.us/hc/en-us/articles/203686015-Using-Q-and-A-in-a-Zoom-Webinar)) can be a really effective way of getting the participants involved (and checking how far people have progressed).

Will we have access to such a tool for this tutorial?

**Comment by crazy4pi314** [comment]
What do you think about discussions on the github page? There are polls we can setup for progress checks, Q&A we can have up on a screen?

**Comment by ltalirz** [comment]
Again, what a great idea! Thank you @crazy4pi314 !
