### ISSUE TITLE
add MD file for presenters

### ISSUE THREAD

**Issue by ltalirz** [crazy4pi314/scipy-vscode-tutorial#9]
detailing how to prepare the setup, e.g.

- liveshare: can we auto-accept new participants?
- [screencast mode](https://www.youtube.com/watch?v=iHLy8Lstopg): showing keystrokes

**Comment by crazy4pi314** [comment]
Love this idea, I'll get something started now (unless I missed you started one already :) )

**Comment by crazy4pi314** [comment]
I put some notes in the [repo wiki](https://github.com/crazy4pi314/scipy-vscode-tutorial/wiki), can add directly to repo if needed, but it ended up feeling kidna akward there.

**Comment by ltalirz** [comment]
That's much better, fully agree!
